"use client"
import styles from "./page.module.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function TOS() {

    return (
        <>
            <Header />

            <div id="tos">
                <h3>Terms of Service</h3>
                <strong>MyHytechEnergy.com Terms of Service</strong>
                <strong>Last updated: March 2, 2019</strong>
                <p>
                    IMPORTANT: The section below titled “Dispute Resolution & Arbitration” requires you to arbitrate claims you may have against Hytech Energy Inc. ("Hytech Energy" or "we"), meaning you cannot bring claims against Hytech Energy in court, and confirms your agreement to a class action waiver in arbitration. It affects your legal rights. Please read it carefully.
                </p>
                <p>
                    Welcome to myhytechenergy.com. These Terms of Service (the "Terms") are a binding legal agreement between you and Hytech Energy, regarding your use of our websites (including www.myhytechenergy.com and www.myhytechenergy.com), our mobile application (myHytech Energy), and our services, including our services available through our online tools (the website and services are collectively referred to as the "Service"). Please read these Terms carefully.
                    In addition, when using certain features of the Service, such as the Free Quote Initiator we make available, you also will be subject to any additional guidelines, terms, or agreements applicable to such features ("Policies"). All such Policies are incorporated by reference into these Terms. If these Terms are inconsistent with any Policy, the terms in the Policy will control.
                    We may periodically make changes to these Terms. By accessing or using the Service or downloading and installing the application, you accept these Terms and any modifications that we may make to these Terms. It is your responsibility to review the most recent version of the Terms frequently and remain informed of any changes to it. If you continue to use the Service after we modify these Terms, you will be deemed to have consented to terms of the modified Agreement for your use of the Service as of the date of the modification. If you do not agree with any provision of these Terms, you must not use the Service.
                </p>
                <ol>
                    <li>
                        The Service. Hytech Energy provides a simple and affordable option for homeowners who want to switch to solar energy. Homeowners can receive free quotes for home solar solutions. Hytech Energy partners with top PV panel supplier companies to install solar systems. Hytech Energy monitors the performance of your system and provides full insurance and a money-back performance guarantee. Hytech Energy delivers an assortment of services through the Service, including the ability for customers to pay their Hytech Energy bill and view the output of their solar power system.
                    </li>
                    <li>
                        Eligibility. You must be 18 years of age or older to use the Service. Use of the Service is void where prohibited. You represent and warrant that any profile information you submit is true and accurate and that you are 18 years of age or older and are fully able and competent to enter into and abide by these Terms. The Services are not intended for those under the age of 18.
                    </li>
                    <li>
                        Promotions. As a part of the Service, we may email or provide you offers and other specials from Hytech Energy or from third parties (collectively "Promotions"). Promotions may expire, and are otherwise subject to change without notice. We have no control over their legality or the ability of any third-party to conduct or honor a Promotion (including the sale in accordance with the offer).
                    </li>
                    <li>
                        Use of Data. Depending on your user settings and what information you provide us, Hytech Energy may help you monitor your home solar power system by providing you with data, including statistics about your solar power system, projections about future usage, or statistics about your monthly invoices ("Data"). While the Data may represent how your solar system is functioning, the Data is not strictly used in the calculation of your monthly invoices. Also, some of the Data may not post to the Service immediately (e.g., your system output). Any Data on the Service is for informational purposes only. Hytech Energy does not confirm the accuracy of any Data posted to the Service. Hytech Energy is not responsible for your use of the Data.
                    </li>
                    <li>
                        Credit Tool. Hytech Energy may provide you the opportunity to run a credit report through a third party ("Credit Tool"). To use the Credit Tool, you must provide certain personal information, including financial information. By using the Credit Tool, you consent to Hytech Energy using your consumer report to help determine if you qualify for certain features of the Service.
                    </li>
                    <li>
                        Use Restrictions. You will not: (a) use the Service for any commercial purpose (unless you have entered into a separate agreement with Hytech Energy expressly permitting commercial use); (b) use the Service to "stalk" or harass any person; (c) access, monitor, or copy any content or information on the Service using any robot, spider, scraper, or other automated means or any manual process, including phishing, for any purpose without our express written permission; (d) violate the restrictions in any robot exclusion headers on the Service or bypass or circumvent other measures employed to prevent or limit access to the Service; (e) take any action that imposes, or may impose, in our sole discretion, an unreasonable or disproportionately large load on our infrastructure; (f) "frame," "mirror," or otherwise incorporate any part of the Service into any other website without our prior written authorization; or (g) intentionally or unintentionally violate any applicable local, state, national, or international law or regulation.
                    </li>
                    <li>
                        If you post material on or through the Service, then, unless we indicate otherwise, you: (a) grant us and our subsidiaries and affiliates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display such material throughout the world in any media; (b) grant us and our affiliates, subsidiaries, and sublicensees the right to use the name that you submit in connection with such material, if we choose; and (c) represent and warrant that you own and control all of the rights to the material that you post, or you otherwise have the right to post such material to the Service; and the use and posting of material you supply, by you or by us, does not violate these Terms, will not violate any rights of or cause injury to any person or entity, and will not otherwise create any harm or liability of any type for us or for third parties.
                    </li>
                    <li>
                        Modifications to the Service. Hytech Energy reserves the right to modify, discontinue, and restrict, temporarily or permanently, all or part of the Service without notice in our sole discretion. Neither we nor our suppliers or licensors will be liable to you or to any third party for any modification, discontinuance, or restriction of the Service.
                    </li>
                    <li>
                        Feedback. Any materials, including but not limited to comments, suggestions, ideas, or other information, provided by you in the form of email or other submissions to us (collectively "Feedback"), are non-confidential and you hereby grant to us and our subsidiaries and affiliates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use your Feedback for any purpose without compensation or attribution to you.
                    </li>
                    <li>
                        Copyright Infringement. We respect the intellectual property rights of others, and ask you to do the same. It is our policy to terminate the access privileges of those who infringe the copyright rights of others. If you believe that your work has been posted on the Service in a way that constitutes copyright infringement, please contact us at the address below and provide the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed, and identification of the time(s) and date(s) the material that you claim is infringing was displayed on the Service; (3) your address, telephone number, and email address; (4) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (5) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.

                        If you believe that your user content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use the content in your user content, you may send a counter-notice containing the following information to the copyright agent: (1) your physical or electronic signature; (2) identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled; (3) a statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content; (4) your name, address, telephone number, and e-mail address; and (5) a statement that you consent to the jurisdiction of the federal court in San Francisco, California and will accept service of process from the person who provided notification of the alleged infringement. If a counter-notice is received by the copyright agent, we may send a copy of the counter-notice to the original complaining party informing that person that we may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion. Our designated agent for notice of copyright infringement can be reached at customercare@myhytechenergy.com
                    </li>
                    <li>
                        Trademarks. Hytech Energy, the Hytech Energy logo, and any other product or service name or slogan contained on the Service are trademarks or registered trademarks of Hytech Energy and its suppliers or licensors, and may not be copied, imitated or used, in whole or in part, without the prior written permission of the applicable trademark holder. All other trademarks, registered trademarks, product names and company names or logos mentioned on the Service are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise, does not constitute or imply endorsement, sponsorship, or recommendation thereof by us, or vice versa.
                    </li>
                    <li>
                        Ownership. We, our affiliates, and our suppliers and licensors own all right, title, and interest, including all intellectual property rights, in and to the Service. Except for those rights expressly granted in these Terms, no other rights are granted, either express or implied, to you.
                    </li>
                    <li>
                        Third-Party Content. The Service may contain links to Web pages and content of third parties ("Third-Party Content") as a service to those interested in this information. We do not monitor, endorse, or adopt, or have any control over, any Third-Party Content. We undertake no responsibility to update or review any Third-Party Content and can make no guarantee as to its accuracy or completeness. Additionally, if you follow a link or otherwise navigate away from the Service, please be aware that these Terms will no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any Third-Party Content provider to which you navigate from the Service. You access and use Third-Party Content at your own risk. The Service may contain advertisements and promotions from third parties. Your business dealings or correspondence with, or participation in promotions of, advertisers other than us, and any terms, conditions, warranties, or representations associated with such dealings, are solely between you and such third party.
                    </li>
                    <li>
                        Privacy Policy. We collect registration and other information about you through the Service, when you choose to provide it to us, and automatically. Our collection and use of this information is described in the Privacy Policy available at https://www.myhytechenergy.com/privacy.
                    </li>
                    <li>
                        Indemnification. You will defend, indemnify and hold harmless Hytech Energy, its subsidiaries, affiliates, partners and third-party advertisers and their respective directors, officers, agents, employees, licensors, and suppliers from and against any costs, damages, expenses, and liabilities (including, but not limited to, reasonable attorneys' fees) arising out of or related to your use of the Service, your violation of these Terms, or your violation of any rights of a third party.
                    </li>
                    <li>
                        Disclaimer of Warranties. YOUR USE OF THE SERVICE, INCLUDING, WITHOUT LIMITATION, YOUR USE OF ANY CONTENT ACCESSIBLE THROUGH THE SERVICE AND YOUR INTERACTIONS AND DEALINGS WITH ANY SERVICE USERS, IS AT YOUR SOLE RISK. THE SERVICE, AND ALL CONTENT AVAILABLE ON AND THROUGH THE SERVICE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULLEST EXTENT ALLOWABLE BY APPLICABLE LAW, HYTECH ENERGY AND ITS SUPPLIERS AND LICENSORS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. HYTECH ENERGY DOES NOT WARRANT UNINTERRUPTED USE OR OPERATION OF THE SERVICE OR YOUR ACCESS TO ANY CONTENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE SERVICE WILL CREATE ANY WARRANTY THAT IS NOT EXPRESSLY STATED IN THESE TERMS. SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OF IMPLIED WARRANTIES, AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION. WITHOUT LIMITING THIS SECTION, HYTECH ENERGY MAKES NO WARRANTIES WHATSOEVER, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, TIMELINESS, OR USEFULNESS OF ANY INFORMATION CONTAINED OR REFERENCED IN THE SERVICE, INCLUDING ANY DATA. TECHNOLOGY CHANGES FREQUENTLY AND THEREFORE INFORMATION CONTAINED ON THE SERVICE MAY BE OUTDATED, INCOMPLETE OR INCORRECT. HYTECH ENERGY DOES NOT ASSUME ANY RISK WHATSOEVER FOR YOUR USE OF THE SERVICE OR THE DATA CONTAINED ON THE SERVICE.
                    </li>
                    <li>
                        Limitation of Liability. TO THE FULLEST EXTENT ALLOWABLE BY APPLICABLE LAW, NEITHER HYTECH ENERGY NOR ITS SUPPLIERS OR LICENSORS WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES (EVEN IF HYTECH ENERGY OR ANY SUPPLIER OR LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF THESE DAMAGES), ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY CONTENT. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. TO THE FULLEST EXTENT ALLOWABLE BY APPLICABLE LAW, THE MAXIMUM TOTAL LIABILITY OF HYTECH ENERGY AND ITS SUPPLIERS AND LICENSORS TO YOU FOR ALL CLAIMS UNDER THESE TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS ONE HUNDRED DOLLARS ($100). EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS TO ALLOCATE THE RISKS UNDER THESE TERMS BETWEEN THE PARTIES. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.
                    </li>
                    <li>
                        Consent to Electronic Communications. By using the Service, you consent to receiving electronic communications from us. These communications may include notices about your account and information concerning or related to the Service. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing.
                    </li>
                    <li>
                        General Legal Notices. Our failure to act in a particular circumstance does not waive our ability to act with respect to that circumstance or similar circumstances. Any provision of these Terms that is found to be invalid, unlawful, or unenforceable will be severed from these Terms, and the remaining provisions of these Terms will continue to be in full force and effect. The section headings and titles in these Terms are for convenience only and have no legal or contractual effect. Any provision in these Terms that by its nature should survive the termination of your license to access the Service or any termination of these Terms (including, without limitation, provisions governing indemnification, limitations on liability, disclaimers of warranty, and ownership of intellectual property) will continue to remain in full force and effect after any such termination. These Terms, including all Policies, constitute the entire agreement between you and Hytech Energy concerning the Service. These Terms supersede all prior agreements or communications between you and Hytech Energy regarding the subject matter of these Terms.
                    </li>
                    <li>
                        Dispute Resolution & Arbitration. Please read this section carefully. It may significantly affect your legal rights, including your right to file a lawsuit in court. These Terms are governed by the laws of the State of California, excluding conflict of laws principles. YOU AND HYTECH ENERGY AGREE TO RESOLVE ANY CONTROVERSY OR CLAIM ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS BY BINDING, BILATERAL ARBITRATION IN ACCORDANCE WITH THE COMMERCIAL ARBITRATION RULES OF THE AMERICAN ARBITRATION ASSOCIATION, BEFORE A NEUTRAL ARBITRATOR INSTEAD OF IN A COURT BY A JUDGE OR JURY, AND YOU AGREE THAT YOU ARE EACH WAIVING THE RIGHT TO SUE IN COURT AND TO HAVE A TRIAL BY JURY. YOU AND HYTECH ENERGY AGREE THAT ANY ARBITRATION WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED, AND YOU ARE AGREEING TO GIVE UP THE ABILITY TO PARTICIPATE IN A CLASS ACTION.

                        You and Hytech Energy agree that the arbitration will be conducted in Fresno County, California and judgment on the arbitration award may be entered into any court of competent jurisdiction. The award of the arbitrator will be final and binding upon the parties without appeal or review except as permitted by California law. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Notwithstanding any of the foregoing, nothing in these Terms of Service will preclude you from bringing issues to the attention of federal, state, or local agencies, and, if the law allows, they can seek relief against us for you.
                    </li>
                    <li>
                        Questions & Contact Information. If you have any questions or concerns about the Service, or these Terms, you may email us at info@myhytechenergy.com
                    </li>
                </ol>
            </div>

            <Footer />
        </>
    );
}
